api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    path('request-dump/', views.request_dump, name='request-dump'),
    path('sw-deploy/', views.sw_deploy, name='sw-deploy'),
    path('sot-populate/', views.sot_populate, name='sot-populate'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

net2d/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('devctrl/', include('api.urls')),
    path('portal/', include('portal.urls')),
    path('dhcpctrl/', include('dhcpctrl.urls')),
    path('admin/', admin.site.urls),
]

portal/urls.py
from django.urls import path
from portal import views

app_name = 'portal'
urlpatterns = [
    path('install/', views.index, name='index'),
    path('install/success', views.success, name='install-success'),
]

portal/models.py
from django.db import models

# Create your models here.

portal/forms.py
from django import forms

class InstallForm(forms.Form): 
    netbox_hostname = forms.CharField(max_length=80, initial='192.168.3.105')
    netbox_port = forms.IntegerField(initial=8080)
    netbox_api_token = forms.CharField(max_length=120, initial='0123456789abcdef0123456789abcdef01234567')
    vlan_id = forms.IntegerField(initial=802)
    vlan_name = forms.CharField(max_length=80, initial='net2d-lab')
    prefix4 = forms.CharField(max_length=120, initial='192.168.3.0/24')
    prefix6 = forms.CharField(max_length=120, initial='2001:db8:cafe::/64')
    device_name = forms.CharField(max_length=120, initial='sw-lab-01')
    device_address4 = forms.CharField(max_length=120, initial='192.168.3.82/24')
    device_address6 = forms.CharField(max_length=120, initial='2001:db8:cafe::196/64')
    

portal/views.py
import logging
import pynetbox
from ipaddress import ip_interface
from django.shortcuts import render, redirect
from portal.forms import InstallForm
from api.models import Sot

logger = logging.getLogger(__name__)

def index(request):
    context = {}

    form = InstallForm()

    if request.method == 'POST':
        form = InstallForm(request.POST)
        if form.is_valid():
            logger.info('Formulário válido!')

            # Salva a SoT
            sot, created = Sot.objects.update_or_create(
                name="netbox-lab",
                defaults={}
                )
            sot.hostname = form.cleaned_data.get("netbox_hostname")
            sot.port = form.cleaned_data.get("netbox_port")
            sot.token = form.cleaned_data.get("netbox_api_token")
            sot.save()

            # Instancia cliente API Netbox
            netbox_url = "http://" + sot.hostname + ":" + str(sot.port) + "/"
            netbox_token = sot.token

            netbox = pynetbox.api(
                netbox_url,
                token=netbox_token
            )
            
            netbox.http_session.verify = False


            ###########################################
            #### Criação de Vlans fictícias Netbox ####
            ###########################################
            for i in range(100,102):
                vlan = {
                    "vid": i,
                    "name": "vlan" + str(i),
                    "status": "active",

                }

                try:
                    nb_vlan = netbox.ipam.vlans.create(vlan)
                except pynetbox.RequestError as e:
                    logger.error("Não foi possível criar a Vlan")
                    logger.error("Erro: " + e.error)

                logger.info("Criada Vlan: " + str(nb_vlan.vid))

                ## Prefixos ficticios
                prefix = {
                    "vlan": nb_vlan.id,
                    "prefix": "192.168." + str(i) + ".0/24",
                    "status": "active"
                }
                try:
                    nb_prefix = netbox.ipam.prefixes.create(prefix)
                except pynetbox.RequestError as e:
                    logger.error("Não foi possível criar o Prefixo")
                    logger.error("Erro: " + e.error)

                logger.info("Criado Prefixo: " + str(nb_prefix.id))

                network = ip_interface(nb_prefix.prefix).network

                for i in range(5,26):
                    address4 = {
                    "address": network[i].compressed,
                    "status": "active",
                    }
                    try:
                        nb_address4 = netbox.ipam.ip_addresses.create(address4)
                    except pynetbox.RequestError as e:
                        logger.error("Não foi possível criar Address4")
                        logger.error("Erro: " + e.error)
                    logger.info("Criad Address4: " + nb_address4.address)

            ##############################################
            #### Criação da Vlan do Usuário no Netbox ####
            ##############################################
            vlan = {
                "vid": form.cleaned_data.get("vlan_id"),
                "name": form.cleaned_data.get("vlan_name"),
                "status": "active",

            }

            try:
                nb_vlan = netbox.ipam.vlans.create(vlan)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar a Vlan")
                logger.error("Erro: " + e.error)

            logger.info("Criada Vlan: " + str(nb_vlan.vid))

            
            ###########################################
            #### Criação do Prefixo IPv4 no Netbox ####
            ###########################################
            prefix4 = {
                "prefix": form.cleaned_data.get("prefix4"),
                "status": "active",
                "vlan": nb_vlan.id,
            }

            try:
                nb_prefix4 = netbox.ipam.prefixes.create(prefix4)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar o Prefixo IPv4")
                logger.error("Erro: " + e.error)

            logger.info("Criado Prefixo IPv4: " + str(nb_prefix4.prefix))


            ###########################################
            #### Criação do Prefixo IPv6 no Netbox ####
            ###########################################
            prefix6 = {
                "prefix": form.cleaned_data.get("prefix6"),
                "status": "active",
                "vlan": nb_vlan.id,
            }

            try:
                nb_prefix6 = netbox.ipam.prefixes.create(prefix6)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar o Prefixo IPv6")
                logger.error("Erro: " + e.error)

            logger.info("Criado Prefixo IPv6: " + str(nb_prefix6.prefix))


            ###########################################
            #### Criação do Dispositivo no Netbox ####
            ###########################################
            
            ### Site ###
            site = {
                "name": "Laboratório",
                "slug": "laboratorio",
                "status": "active",
            }
            try:
                nb_site = netbox.dcim.sites.create(site)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar o Site")
                logger.error("Erro: " + e.error)
            logger.info("Criado Site: " + nb_site.name)


            ### Device Role ###
            device_role = {
                "name": "Teste Net2d",
                "slug": "teste-net2d",
                "color": "9e9e9e",
            }
            try:
                nb_device_role = netbox.dcim.device_roles.create(device_role)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar o Device Role")
                logger.error("Erro: " + e.error)
            logger.info("Criado Device Role: " + nb_device_role.name)


            ### Manufacturer ###
            manufacturer = {
                "name": "Mikrotik",
                "slug": "mikrotik",
            }
            try:
                nb_manufacturer = netbox.dcim.manufacturers.create(manufacturer)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar Manufacturer")
                logger.error("Erro: " + e.error)
            logger.info("Criado Manufacturer: " + nb_device_role.name)


            ### Device Type ###
            device_type = {
                "manufacturer": nb_manufacturer.id,
                "model": "Cloud Hosted Router",
                "slug": "chr",
                "u_height": 1.0,
            }
            try:
                nb_device_type = netbox.dcim.device_types.create(device_type)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar Device Type")
                logger.error("Erro: " + e.error)
            logger.info("Criado Device Type: " + nb_device_type.model)


            ### Platform ###
            platform = {
                "name": "Router OS",
                "slug": "mikrotik_routeros",
                "manufacturer": nb_manufacturer.id,
            }
            try:
                nb_platform = netbox.dcim.platforms.create(platform)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar Platform")
                logger.error("Erro: " + e.error)
            logger.info("Criada Platform: " + nb_device_type.model)


            ### Device ###
            device = {
                "name": form.cleaned_data.get("device_name"),
                "role": nb_device_role.id,
                "device_type": nb_device_type.id,
                "platform": nb_platform.id,
                "site": nb_site.id,
                "status": "active", 
            }
            try:
                nb_device = netbox.dcim.devices.create(device)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar Device")
                logger.error("Erro: " + e.error)
            logger.info("Criado Device: " + nb_device.name)

            ### Interfaces Físicas
            for i in range(1,5):
                interface = {}
                interface["device"] = nb_device.id
                interface["name"] = "ether" + str(i)
                interface["type"] = "1000base-t"
                try:
                    nb_interface = netbox.dcim.interfaces.create(interface)
                except pynetbox.RequestError as e:
                    logger.error("Não foi possível criar Interface")
                    logger.error("Erro: " + e.error)
                logger.info("Criada Interface: " + nb_interface.name)
                      
            
            ### IP de Gerência ###
            #### IPv4 de Gerência ####
            nb_interface = netbox.dcim.interfaces.get(name="ether1")
            address4 = {
                "address": form.cleaned_data.get("device_address4"),
                "status": "active",
                "assigned_object_type": "dcim.interface",
                "assigned_object_id": nb_interface.id,
            }
            try:
                nb_address4 = netbox.ipam.ip_addresses.create(address4)
            except pynetbox.RequestError as e:
                logger.error("Não foi possível criar Address4")
                logger.error("Erro: " + e.error)
            logger.info("Criad Address4: " + nb_address4.address)

            ### Atualiza Device ###
            nb_device.primary_ip = nb_address4.id
            nb_device.primary_ip4 = nb_address4.id
            nb_device.save()


            # ### Custom Link (Botão Net2d) ###
            # custom_link = {

portal/templates/portal/base_page.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    {% block title %}<title>Net2d</title>{% endblock %}
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <main>
        <nav class="navbar bg-success border-bottom border-body">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'portal:index' %}">Net2d</a>
            </div>
          </nav>
        {% block content %}{% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/ef34d0a07b.js" crossorigin="anonymous"></script>
</body>

</html>

portal/templates/portal/index.html
{% extends "portal/base_page.html" %}

{% load static %}

{% block content %}
<div class="container">
  <div class="card mt-3">
    <div class="card-header bg-success-subtle">
      <div class="d-flex">
        <strong>Instalação</strong>
      </div>
    </div>
    <div class="card-body py-3 px-1">
        <div class="card-body">
          <h5 class="card-title">Olá,</h5>
          <p class="card-text">Insira as informações abaixo para criar um ambiente mínimo no Netbox para testar o Net2d.</p>
          <form action="{% url 'portal:index' %}" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col">
                <div class="mb-3">
                  <div class="row">
                    <div class="col-8">
                      <label for="inputNetboxHostname" class="form-label">IP Netbox</label>
                      <input type="text" class="form-control" id="inputNetboxHostname1" aria-describedby="urlHelp" name="netbox_hostname" value="{{ form.netbox_hostname.value}}">
                      <div id="netboxHostname" class="form-text">Ex.: 143.54.235.23</div>
                    </div>
                    <div class="col-4">
                      <label for="inputNetboxPort" class="form-label">Porta</label>
                      <input type="number" class="form-control" id="inputNetboxPort" aria-describedby="netboxPortHelp" name="netbox_port" value="{{ form.netbox_port.value}}">
                      <div id="netboxPortHelp" class="text">Ex.: 8080</div>
                    </div>
                  </div>
                </div>
                <div class="mb-3">
                  
                </div>
                <div class="mb-3">
                  <label for="inputToken" class="form-label">Token API</label>
                  <input type="text" class="form-control" id="inputToken" name="netbox_api_token" value="{{ form.netbox_api_token.value}}">
                  <div id="tokenHelp" class="form-text">Acesse o Netbox em: "Admin" > "API Tokens"</div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="card">
                  <div class="card-header">
                    <strong>Network</strong>
                  </div>
                  <div class="card-body">
                    <div class="row">
                      <div class="col-4">
                        <div class="mb-3">
                          <label for="inputVlan" class="form-label">Vlan Id:</label>
                          <input type="number" class="form-control" id="inputVlan" name="vlan_id" value="{{ form.vlan_id.value}}">
                          <div id="vlanHelp" class="form-text">Id da Vlan</div>
                        </div>
                      </div>
                      <div class="col-8">
                        <div class="mb-3">
                          <label for="inputVlan" class="form-label">Nome da Vlan:</label>
                          <input type="text" class="form-control" id="inputVlan" name="vlan_name" value="{{ form.vlan_name.value}}">
                          <div id="vlanHelp" class="form-text">Ex: laboratorio-net2d</div>
                        </div>
                      </div>
                    </div>
                    <div class="mb-3">
                      <label for="inputPrefix4" class="form-label">Prefixo IPv4:</label>
                      <input type="text" class="form-control" id="inputPrefix4" name="prefix4" value="{{ form.prefix4.value}}">
                      <div id="prefix4Help" class="form-text">Ex.: 192.168.2.0/24</div>
                    </div>
                    <div class="mb-3">
                      <label for="inputPrefix6" class="form-label">Prefixo IPv6:</label>
                      <input type="text" class="form-control" id="inputPrefix6" name="prefix6" value="{{ form.prefix6.value}}">
                      <div id="prefix6Help" class="form-text">Ex: 2001:db8:cafe::/64</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card">
                  <div class="card-header">
                    <strong>Device</strong>
                  </div>
                  <div class="card-body">
                    <div class="mb-3">
                      <label for="inputDeviceName" class="form-label">Nome do dispositivo:</label>
                      <input type="text" class="form-control" id="inputDeviceName" name="device_name" value="{{ form.device_name.value}}">
                      <div id="deviceNameHelp" class="form-text">Ex.: sw-lab-01</div>
                    </div>
                    <div class="mb-3">
                      <label for="inputAddress4" class="form-label">IP Gerência IPv4:</label>
                      <input type="text" class="form-control" id="inputAddress4" name="device_address4" value="{{ form.device_address4.value}}">
                      <div id="address4Help" class="form-text">Ex.: 192.168.3.196/24</div>
                    </div>
                    <div class="mb-3">
                      <label for="inputAddress6" class="form-label">IP Gerência IPv6</label>
                      <input type="text" class="form-control" id="inputAddress6" name="device_address6" value="{{ form.device_address6.value}}">
                      <div id="address6Help" class="form-text">Ex: 2001:db8:cafe::196/64</div>
                    </div>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-success mt-4">OK</button>
          </form>
        </div>
      </div>
    </div>
    <div class="card-footer mt-4">
      <div class="text-center">
        <kbd class="text-success">Net2d</kbd>
      </div>
    </div>
  </div>
</div>
{% endblock %}

portal/templates/portal/success.html
{% extends "portal/base_page.html" %}

{% load static %}

{% block content %}
<div class="container">
  <div class="card mt-3">
    <div class="card-header bg-success-subtle">
      <div class="d-flex">
        <strong>Instalação</strong>
      </div>
    </div>
    <div class="card-body py-3 px-1">
        <div class="card-body">
          <h5 class="card-title">Sucesso</h5>
        </div>
      </div>
    </div>
    <div class="card-footer mt-4">
      <div class="text-center">
        <kbd class="text-success">Net2d</kbd>
      </div>
    </div>
  </div>
</div>
{% endblock %}